### ISSUE TITLE
Chapter 4: Error in `TestWriteToFile_WritesGivenDataToFile`

### ISSUE THREAD

**Issue by cassamajor** [bitfield/tpg-tools2#4]
Hilariously, the section titled "*A disastrous bug*" contains a bug itself.

- When we add `_, err := os.Stat(path)`
- `err := writer.WriteToFile(path, want)` is left unmodified
- resulting in: `no new variables on left side of :=`

This erroneous code seems to only be in the book, not in the code examples in this repository.

**Comment by bitfield** [comment]
Good spotting, @cassamajor, but this has already been fixed—I recommend you upgrade to the latest edition!

https://bitfieldconsulting.com/books/tools
