### ISSUE TITLE
Bug: weather tool doesn't work correctly with multi-word cities

### ISSUE THREAD

**Issue by linhns** [bitfield/tpg-tools2#5]
Considering [weather/6](https://github.com/bitfield/tpg-tools2/tree/main/weather/6), the formatted URL by `weather.(Client).FormatURL` will result in a `400 Bad Request`.

My fix was to escape the location string with `url.QueryEscape`.

```
func (c Client) FormatURL(location string) string {
	return fmt.Sprintf("%s/data/2.5/weather?q=%s&appid=%s", c.BaseURL, url.QueryEscape(location), c.APIKey)
}
```

**Comment by bitfield** [comment]
Thanks for the report! Looks like OpenWeather changed the validation requirements on the query URL. Now fixed.
